{% set name = "pydy" %}
{% set version = "0.5.0" %}
{% set sha256 = "1b487a62b55a8c8664009b09bf789254b2c942cd704a380bedb1057418c94fa2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: pydy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools >=20.7.0
  run:
    - python
    - setuptools >=20.7.0
    - sympy >=0.7.6.1
    - numpy >=1.11.0
    - scipy >=0.17.1
    - pywin32  # [win]

test:
  imports:
    - pydy
    - pydy.codegen
    - pydy.codegen.tests
    - pydy.models
    - pydy.system
    - pydy.utils
    - pydy.viz
    - pydy.viz.tests

about:
  home: http://pydy.org
  license: BSD-3-Clause
  summary: 'Python tool kit for multi-body dynamics.'

extra:
    recipe-maintainers:
        - moorepants
