{% set name = "pydy" %}
{% set version = "0.4.0" %}
{% set sha256 = "2c309d17cd9059a98f47c2fd25521b009eacb9e4538e9b1a7cfaf3cd450103b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: pydy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools >=20.7.0
  run:
    - python
    - setuptools >=20.7.0
    - sympy >=0.7.6.1
    - numpy >=1.11.0
    - scipy >=0.17.1

test:
  imports:
    - pydy
    - pydy.codegen
    - pydy.codegen.tests
    - pydy.models
    - pydy.system
    - pydy.utils
    - pydy.viz
    - pydy.viz.tests

about:
  home: http://pydy.org
  license: BSD-3-Clause
  summary: 'Python tool kit for multi-body dynamics.'

extra:
    recipe-maintainers:
        - moorepants
