travis:
  secure:
    BINSTAR_TOKEN: TU5q/XdmoWmARovrRSqBeBTVVTiQPSJ1qyCaG3zVp7CnJ/FriW5iSPfao+6oJLD8v2NbskasLGScB7VvuvUq8BwU1g/tReA3jDr9y/TXE7xQng7TFOP0g4pbQ7s15OH5llVhPycknQwH7nknMB8PnQ9TU819zIsCaH0HEEWotsyVDP+XMw4yV/DmgwmO6f/lvkfQajNfYa/00S/6XKQ+w6M5UFaI/5Ur57ueaZ2BRH36Ipxs2SPY4lnzqG9nlrDGoCHcAp+IGZTFB6vhQY7kquenHEmEsP73xbi5GCaQJu+B3wjpoUN5pI2o3tQyqQr1mgcNDwcfjMkmFKGnslDyC50iAGMqKuqsNLcfAaFKg6iCFC/Bm1y+nS3pnIP0qPU6K3kxXYAyj0YFJLGuUwExP0ec08V1DlAytFVhFltY1V55hgYznbQ65IfOjVvnpPQ+yvxuoetR93Z3su+8RPYy7qIVZGQ7c5L1MZ3EXtiLXZZSFT84xxf5UwSL7MCdC7eQ3/2G6PBiLbGUb//4WnRR5TK1c/OwFwV/yCH3umwWWnjIt4SqrVQ+xEGn0QzPVERDlbsOORU+fP2smMjOoNYtjdHhXRMgSTwIENhGSIlVfvwUorPXRBIOAWjpOkT0/QNum6z/DTxefzBX4jdJhVUvX3nrbJWt0L5AlDaNs25Ztpw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
