travis:
  secure:
    BINSTAR_TOKEN: nGwT0Y6BqnCY4221EgaevGhWxDT/VZG8wqLPMnAqFd+FAU4vHm4ZrG11eLINMweJtv8qMdz8QTSUqqAQfCulbEGid8wwcFE+s0Org4Wj7znQg3wIGTSSGjmLuTEdaPlU75FAjVXO9QEiF9qVsQ3CAnRy4thIbNGj2AU3f54zLO/aDF/aCFSdPcat3AebfMYm3hZA/mzlfeKAAK9WSGK+uhsJL6DzwRgTdZcUS0hY8hbKaSWTKp8Gs2b9tXpq+J9NMO5TPrltvJ9rGjA24l+pIssklJS7V3O8+1LDLsw3ZC1ebyZ9BvMnwNf8QqV6oRxjzqNv1MQE5rCOrrvdhJLGMGiVAIhZ/M2XRdBVVGk00GIC18Loapuk+hWccMNn0By+hz5lCjyVYZ3qD+z8wE3paR1ZRhJjzZg8/Q4Cl23njyKGC7NrSi8Pd2DVJNRKN5HiS4yQH8IDPyQ2iEjuFyIo8Dzk7nyHexUJz+wzoI9dgfJETxSAeH8MkPHuuhJN+vUe/TTSltGpmrdHv2tFD7x0C77WsLq4kBfP09vLDwXGGZ/vZfeYqCv1vMJmYTS94PrlN3i29nZ3nWXEmuo5pcFALaW5CRIHOa3g1gMRlnki6XmCJHOzlnoTU3s7q/o1eAPM7shnaIRJqYTXB0YFgGe1/immVIOdUIPrqwtBwpGCeP4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
