travis:
  secure:
    BINSTAR_TOKEN: kEuSBOyVoGD/bjJOCnNryyeeZ544o3EjEO739Q55z86eIujs/Miup4hT4DHZ2pdna2O6G/5Vg+YlzYnrhvZ12AtusYDtBCDRTHO1fwXE84TiEqqYwLXyQaaCyuq48Y5gRzGsOWGYB9MCy5zcDwiskESZs732wu8usoymq0+fJkHE5VPR37D0JL/Oy9vk3n51fUue5cbGyC4blO3t4mOEOF6/LW8Et0fz5UKFlqgohNRNEZD4lm+LOfGy2YFVwCB3gyIJp9IT6ifYx9IJOxLX12q7yc77EZG7LmsqiJhKr26+NV2V03K2KR/VtNLbtyu2vWA9Tj/s54DkkGXC9ba1mouWXwWcqY56rp4cR4OX5zV23mwwp0iMXa6jpT/nhAfhiWd5AjXgwvnsB+9brE/1Nin1pjfLJOS9iiEFnIdvM2debcRKhIxb8YGbXbp/qxjhXDS5DE17CsZl32f6DeUAXYvaHrUWbx0KNXLNF8wSSVH1soYUObEJAhrDVvLqe3xZO5PxIlbdoYifn5hBoq2N5TqGT3GD6tle0KPBtyHZYNo5bXOMdIyAjTN5L29TkuEPMkZe6jKU95Mb/eFXJg6ybhy5H00z8mS8WLAN3qFXY3UNAROpvVfDNPccMDCHBIS4ZmqtCCB4LYdDbpAAsKiiaVM5j+xbOmFJ0lw/Cvf95hc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
